export let achillesCommendations = [
	"Sting like a bee",
	"Grand Theft",
	"Kicking it Old School",
	"The Reaper",
	"Almost doesn't count",
	"Lucky",
	"Not so tough",
	"Something on your face",
	"Too fast for you",
	"Is there no one else?",
	"I'm just perfect",
	"Forgot to pay the toll",
	"Standard Issue",
	"It's a bird!",
	"Till someone loses an eye",
	"Lawnmower",
	"No Hard Feelings",
	"Look ma no pin",
	"The Pain Train",
	"Road Trip",
	"Power play",
	"From the top rope",
	"So cuddly",
	"First Strike",
	"Sorry mate",
	"Vandalism",
	"From Downtown",
	"Not so fast",
	"Body Guard",
	"Can't we get along?",
	"Deconstructed",
]
